---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: download
  image: golang:1.16
  commands:
  - go mod download
  volumes:
  - name: gopath
    path: /go

- name: lint
  image: golang:1.16
  commands:
  - make lint
  volumes:
  - name: gopath
    path: /go
  depends_on:
  - download

- name: test
  image: golang:1.16
  commands:
  - make test
  volumes:
  - name: gopath
    path: /go
  depends_on:
  - download

---
kind: signature
hmac: 27e9124f010ea02719fed325246799697d827ceb9dcf7d742fb30fb45372b728

...
